import type { Metadata } from "next";
import { Inter } from "next/font/google";
import { Navbar } from "./Navbar/Navbar";
import { ColorSchemeScript,MantineProvider } from '@mantine/core';
import '@mantine/core/styles.layer.css';
import 'mantine-datatable/styles.layer.css';
import "./layout.css";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Book Store",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <MantineProvider  defaultColorScheme="auto">
          <div style={{display:'flex'}}>
            <Navbar />
            <div style={{margin:'10px'}}>
             {children}
            </div>
          </div>
        </MantineProvider>
      </body>
    </html>
  );
}
